name: terracotta
channels:
  - conda-forge
dependencies:
  - python=3.12.0
  - pip
  - jupyterlab
  - numpy
  - tskit
  - tszip
  - scipy
  - ipywidgets
  - tqdm
  - matplotlib
  - msprime
  - pandas
  - geopandas
  - geodatasets
  - h3pandas
  - emcee
  - numba